version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: kamal2002
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - springboot-net
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/practice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kamal2002
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8082
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-net
    restart: always

networks:
  springboot-net:
    driver: bridge
