version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - springboot-net
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DB}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SERVER_PORT: ${APP_PORT}
    depends_on:
      - mysql
    networks:
      - springboot-net
    restart: always

networks:
  springboot-net:
    driver: bridge
