apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
        app: jenkins-demo
    spec:
      containers:
        - name: jenkins-demo-container
          image: kamalahmad/jenkins-demo:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:8091/${MYSQL_DB:practice}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: kamal2002
            - name: SERVER_PORT
              value: "8082"
